spring:
  datasource:
    url: jdbc:mysql://db-mysql-fra1-49936-order-do-user-8611302-0.b.db.ondigitalocean.com:25060/beerorderservice?useUnicode=true&characterEncoding=UTF-8&ssl-mode=REQUIRED
    username: beer_order_service
    password: password


