spring:
  datasource:
#    url: jdbc:mysql://db-mysql-fra1-84455-inventory-do-user-8611302-0.b.db.ondigitalocean.com:25060/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&ssl-mode=REQUIRED
    url: jdbc:mysql://db-mysql-fra1-84455-inventory-do-user-8611302-0.b.db.ondigitalocean.com:25060/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: beer_inventory_service
    password: password


